title: 数理神経科学の世界
description: > # this means to ignore newlines until "baseurl:"
  神経科学を中心に、勉強したことをまとめていきます。
  記事の内容に明らかな誤りがある場合は、Twitter等でお知らせください。
  当サイトの引用はご自由にどうぞ。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://poyaneuro.net" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'lactoneinfo'
  last_name: 'lactoneinfo'
  cv: '//twitter.com/lactoneinfo'
  avatar: '/images/myicon.jpg'
  github_username: lactoneinfo
#  email: vika@kaptn.ru
#  vk_id: id201664979
  telegram_name: 数理神経科学の世界
#  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html

