title: 数理神経科学の世界
description: > # this means to ignore newlines until "baseurl:"
  神経科学で勉強したことをまとめていきます<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://poyaneuro.net" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'lactoneinfo'
#  last_name: 'Kapitonenko'
#  cv: '//kaptn.ru'
  avatar: '/images/myicon.jpg'
  github_username: lactoneinfo
#  email: vika@kaptn.ru
#  vk_id: id201664979
#  telegram_name: vikapitoshka 
#  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html

